name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # JDK Setup
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

        # Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check ktlint format
        run: ./gradlew ktlintCheck

        # Gradle Test를 실행한다
      - name: Test with Gradle
        run: ./gradlew test

      - name: Upload CI results
        uses: actions/upload-artifact@v2
        with:
          name: ci-results
          path: build/ci-results
